### ISSUE TITLE
Expected 'application/wasm'

### ISSUE THREAD

**Issue by alanpoon** [mbasso/react-wasm#10]
**General Information**

- [ ] Bug
- [ ] Improvement
- [x] Feature
- [ X] Other

**Description**
TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

It seems like I cannot instantiate webassemby streaming and I do not know how to add the mime type to the server.

**Versions**

- react:16.8.3
- react-wasm: 1.01
- browser: chrome Version 76.0.3809.132 (Official Build) (64-bit)
- expo: ^34.0.1

**Comment by dwebfan** [comment]
I found similiar issue with the example codes. Can you tell me how you solve it?

**Comment by alanpoon** [comment]
I don't think I am using react-wasm, I am using webpack.config. https://github.com/wasm-tool/wasm-pack-plugin/issues/67

I compile wasm into a npm package first, then import in react. You can refer to https://github.com/scs/substrate-api-client/pull/48#issuecomment-629106462
