### ISSUE TITLE
useWasm hook

### ISSUE THREAD

**Issue by mbasso** [mbasso/react-wasm#3]
The 4th of february react@16.8.0 will be released, and it will contains hooks: facebook/react#14692.
This means that we can develop a `useWasm` hook, as said in #1, a new alternative to the render prop and HoC. Maybe something like:

```js
const { loading, error, data } = useWasm({
  url: '/add.wasm'
});
```

@mfrachet let me know if you are interested in developing this 😄

**Comment by mfrachet** [comment]
Hi!

I'm so sorry to answer you that late, I didn't see the notification pass :/ .

I've started in a new company and don't have that much time to work on this for now. So if you'd like to do it, feel free to 😊

**Comment by mbasso** [comment]
Hi @mfrachet,
thank you for your reply, I'll take a look at this as soon as possile 😄
